FROM centos:7

RUN yum install -y -t \
    tar \
    git \
    make \
    gcc \
    bison \
    autoconf \
    httpd-devel \
    libxml2-devel \  
    openssl-devel \
    bzip2-devel \
    curl-devel \
    libjpeg-devel \
    libpng-devel \
    libXpm-devel \
    freetype-devel \
    t1lib-devel \
    gmp-devel \
    libicu-devel \
    gcc-c++ \
    aspell-devel \
    recode-devel \
    mariadb-devel

    
    #httpd \


#    apache2-mpm-prefork \
#    apache2-prefork-dev \
#    aufs-tools \
#    automake \
#    bison \
#    btrfs-tools \
#    build-essential \
#    curl \
#    git \
#    libbz2-dev \
#    libcurl4-openssl-dev \
#    libmcrypt-dev \
#    libxml2-dev \
#    re2c \
#    libjpeg-dev \
#    libpng12-dev \
#    libxpm-dev \
#    libpcre3-dev \
#    libfreetype6-dev \
#    libmysqlclient-dev \
#    libt1-dev \
#    libgd2-xpm-dev \
#    libgmp-dev \
#    libsasl2-dev \
#    libmhash-dev \
#    unixodbc-dev \
#    freetds-dev \
#    libpspell-dev \
#    libsnmp-dev \
#    libtidy-dev \
#    libxslt1-dev \
#    libmcrypt-dev \
#    libicu-dev \
#    librecode-dev
    
